# Generated by Django 5.2.7 on 2026-09-21 16:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='e.g. SIKA-DSP-2026-001', max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('RETAIL_RECEIPT', 'Sunyani Counter Retail Receipt'), ('WHOLESALE_INVOICE', 'B2B Wholesale Commercial Invoice'), ('INSTITUTIONAL_PROFORMA', 'School Institutional Procurement Proforma')], default='RETAIL_RECEIPT', max_length=30)),
                ('tax_mode', models.CharField(choices=[('RETAIL_NET', 'Retail Mode (Net Flat)'), ('GRA_STANDARD_VAT', 'GRA Standard (15% VAT + 2.5% NHIL + 2.5% GETFund + 1% COVID)'), ('INSTITUTIONAL_WHT_3PCT', 'Institutional Mode (Act 896 3% WHT Deducted)')], default='RETAIL_NET', max_length=30)),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('client_tin', models.CharField(blank=True, help_text='GRA Tax Identification Number (TIN)', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='3% Withholding Tax deduction', max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash Counter'), ('MOMO_TILL', 'MTN Mobile Money Till'), ('TELECEL_CASH', 'Telecel Cash'), ('BANK_TRANSFER', 'GCB / Bank Transfer'), ('TERM_CREDIT', 'Institutional Term Credit (30-Day)')], default='CASH', max_length=25)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='MoMo Transaction ID or Bank Slip Ref', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
    ]
