from django.contrib import admin
from .models import Supplier, InventoryItem, StockMovement


@admin.register(Supplier)
class SupplierAdmin(admin.ModelAdmin):
    list_display = ['name', 'contact_person', 'phone', 'email', 'is_active', 'created_at']
    list_filter = ['is_active', 'created_at']
    search_fields = ['name', 'contact_person', 'phone', 'email']


@admin.register(InventoryItem)
class InventoryItemAdmin(admin.ModelAdmin):
    list_display = [
        'product',
        'supplier',
        'carton_stock',
        'loose_stock',
        'pieces_per_carton',
        'total_retail_pieces_display',
        'total_cost_valuation_display',
        'warehouse_location',
        'updated_at'
    ]
    list_filter = ['product__category', 'supplier', 'warehouse_location']
    search_fields = ['product__name', 'product__sku', 'warehouse_location']
    readonly_fields = [
        'total_retail_pieces',
        'total_cost_valuation',
        'total_retail_valuation',
        'is_low_stock',
        'stock_status_label',
        'created_at',
        'updated_at'
    ]

    fieldsets = (
        ('Product & Supplier', {
            'fields': ('product', 'supplier', 'warehouse_location')
        }),
        ('Packaging Hierarchy', {
            'fields': ('bulk_unit_name', 'retail_unit_name', 'pieces_per_carton')
        }),
        ('Current Physical Stock Balances', {
            'fields': ('carton_stock', 'loose_stock', 'total_retail_pieces', 'is_low_stock', 'stock_status_label')
        }),
        ('Financial Valuation', {
            'fields': ('cost_price', 'total_cost_valuation', 'total_retail_valuation')
        }),
        ('Reorder Thresholds', {
            'fields': ('low_stock_threshold_cartons', 'low_stock_threshold_loose')
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        }),
    )

    def total_retail_pieces_display(self, obj):
        return f"{obj.total_retail_pieces:,} {obj.retail_unit_name}s"
    total_retail_pieces_display.short_description = "Effective Pieces"

    def total_cost_valuation_display(self, obj):
        return f"GH₵ {obj.total_cost_valuation:,.2f}"
    total_cost_valuation_display.short_description = "Cost Valuation"


@admin.register(StockMovement)
class StockMovementAdmin(admin.ModelAdmin):
    list_display = [
        'created_at',
        'item',
        'movement_type',
        'carton_delta',
        'loose_delta',
        'resulting_carton_stock',
        'resulting_loose_stock',
        'reference',
        'created_by'
    ]
    list_filter = ['movement_type', 'created_at', 'item__product__category']
    search_fields = ['item__product__name', 'item__product__sku', 'reference', 'note']
    readonly_fields = [
        'item',
        'movement_type',
        'carton_delta',
        'loose_delta',
        'resulting_carton_stock',
        'resulting_loose_stock',
        'reference',
        'created_by',
        'note',
        'created_at'
    ]

    def has_add_permission(self, request):
        # Stock movements are immutable audit records generated by system actions
        return False
