# Generated by Django 5.2.7 on 2026-09-21 16:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RulingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('EXERCISE', 'Standard Exercise Book'), ('NOTE', 'Note 1 & Note 3 Hardcover'), ('KINDERGARTEN', 'Pre-School & Kindergarten'), ('SPECIALIZED', 'Graph & Sketch Books')], default='EXERCISE', max_length=30)),
                ('page_count', models.PositiveIntegerField(default=80)),
                ('base_unit_price', models.DecimalField(decimal_places=2, help_text='Base price per copy in GH₵', max_digits=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(help_text='e.g. DSP-2026-STJ-0042', max_length=40, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('proprietor_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_location', models.CharField(help_text='Campus or Bus terminal town', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=5000, help_text='MOQ enforced: 5,000 – 10,000 copies recommended')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('3.20'), max_digits=8)),
                ('plate_setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Waived (0.00) for orders >= 1,000 copies', max_digits=8)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('wht_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Statutory 3% GRA WHT Act 896', max_digits=4)),
                ('wht_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('school_crest', models.ImageField(blank=True, null=True, upload_to='crests/')),
                ('back_cover_content', models.TextField(default='School Anthem, School Rules & Regulations, National Pledge')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Quote'), ('PROOF_PENDING', 'Awaiting Digital Proof Approval'), ('PROOF_APPROVED', 'Approved by School Proprietor'), ('PLATE_MAKING', 'Offset Plate & Film Casting'), ('PRINTING', 'High-Speed Printing & Folding'), ('COMPLETED', 'Finished & Packaged'), ('DISPATCHED', 'Dispatched via Regional Bus / Van')], default='PROOF_PENDING', max_length=30)),
                ('digital_proof_approved', models.BooleanField(default=False)),
                ('approved_by_signatory', models.CharField(blank=True, max_length=150)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_orders', to='customizer.rulingoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
