# Generated by Django 5.2.7 on 2026-09-21 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(help_text='e.g. VIP-SNY-8841', max_length=50, unique=True)),
                ('carrier', models.CharField(choices=[('VIP_JEOUN', 'VIP Jeoun Transport'), ('OA_TRAVEL', 'OA Travel and Tours'), ('IMPERIAL_EXPRESS', 'Imperial Express'), ('METRO_MASS', 'Metro Mass Transit (MMT)'), ('CAMPUS_VAN', 'Direct Campus Delivery Van')], default='VIP_JEOUN', max_length=30)),
                ('origin_hub', models.CharField(default='Sunyani Main Hub', max_length=100)),
                ('destination_town', models.CharField(help_text='e.g. Kumasi (Asafo), Tamale, Takoradi', max_length=100)),
                ('recipient_name', models.CharField(help_text='Institution or Bookshop contact', max_length=150)),
                ('recipient_phone', models.CharField(max_length=50)),
                ('consignment_summary', models.CharField(help_text='e.g. 12 Heavy Cartons of 80pg Exercise Books', max_length=255)),
                ('driver_conductor_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked at Sunyani Terminal'), ('IN_TRANSIT', 'In Transit on Route'), ('ARRIVED_AT_TERMINAL', 'Arrived at Destination Terminal'), ('DELIVERED_AND_SIGNED', 'Delivered & Consignment Signed')], default='BOOKED', max_length=30)),
                ('sms_alert_sent', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regional Bus Waybill',
                'verbose_name_plural': 'Bus Waybill & Regional Dispatch Tracker',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('location', models.CharField(default='Sunyani', max_length=150)),
                ('principal_name', models.CharField(help_text='Headmaster or Bursar name', max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
                ('academic_term', models.CharField(default='Term 1 (2026/2027 Academic Year)', max_length=100)),
                ('total_credit_granted', models.DecimalField(decimal_places=2, help_text='Total invoiced on credit in GH₵', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total installments received in GH₵', max_digits=12)),
                ('balance_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining debt balance', max_digits=12)),
                ('term_due_date', models.DateField()),
                ('status', models.CharField(choices=[('CURRENT', 'Current / In Good Standing'), ('PARTIALLY_PAID', 'Partially Paid'), ('FULLY_SETTLED', 'Fully Settled'), ('OVERDUE_NOTICE', 'Overdue Notice Issued')], default='CURRENT', max_length=30)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Credit Record',
                'verbose_name_plural': 'School Credit & Receivables Ledger',
                'ordering': ['-balance_outstanding'],
            },
        ),
    ]
