# Generated by Django 5.0.1 on 2026-09-23 20:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company or distributor name', max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Warehouse location or supply depot')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit manufacturing or landed procurement cost per retail piece (GH₵)', max_digits=10)),
                ('bulk_unit_name', models.CharField(default='Carton', help_text='Wholesale bulk packaging title (e.g. Carton, Box, Pack)', max_length=50)),
                ('retail_unit_name', models.CharField(default='Piece', help_text='Individual retail shelf unit title (e.g. Book, Piece, Ream)', max_length=50)),
                ('pieces_per_carton', models.PositiveIntegerField(default=120, help_text='Number of loose retail units contained inside 1 sealed bulk carton/box')),
                ('carton_stock', models.PositiveIntegerField(default=0, help_text='Sealed bulk cartons currently in warehouse storage')),
                ('loose_stock', models.PositiveIntegerField(default=0, help_text='Loose shelf pieces available for direct walk-in retail counter sales')),
                ('low_stock_threshold_cartons', models.PositiveIntegerField(default=3, help_text='Minimum sealed bulk cartons before triggering warehouse restock alert')),
                ('low_stock_threshold_loose', models.PositiveIntegerField(default=15, help_text='Minimum shelf pieces before triggering auto break-bulk unbox alert')),
                ('warehouse_location', models.CharField(default='Sunyani Main Hub — Shelf A1', help_text='Physical shelf, bay, or room location in Sunyani warehouse', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(help_text='Associated product in the public and wholesale catalog', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Inventory Item & Stock Balance',
                'verbose_name_plural': 'Inventory Items & Stock Balances',
                'ordering': ['product__category__name', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RESTOCK_IN', 'Restock / Supplier Inflow'), ('POS_SALE', 'Counter POS Sale Out'), ('B2B_SALE', 'B2B Wholesale Dispatch'), ('BREAK_BULK', 'Break-Bulk Unboxing (Carton → Shelf)'), ('ADJUSTMENT', 'Stocktake Physical Audit Adjustment'), ('DAMAGE', 'Damaged / Write-Off'), ('RETURN', 'Customer Return Restock')], default='POS_SALE', max_length=20)),
                ('carton_delta', models.IntegerField(default=0, help_text='Net change in bulk cartons (+ for restock, - for sale or unboxing)')),
                ('loose_delta', models.IntegerField(default=0, help_text='Net change in shelf pieces (+ for restock/unboxing, - for retail sale)')),
                ('resulting_carton_stock', models.PositiveIntegerField(help_text='Carton balance immediately after this movement')),
                ('resulting_loose_stock', models.PositiveIntegerField(help_text='Loose piece balance immediately after this movement')),
                ('reference', models.CharField(blank=True, help_text='POS Receipt #, Invoice #, or Waybill Reference', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who processed the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Movement Ledger Record',
                'verbose_name_plural': 'Stock Movement Ledger Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
