# Generated by Django 5.2.7 on 2026-09-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-book', help_text='Font Awesome 6 icon class', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('retail_price', models.DecimalField(decimal_places=2, help_text='Price per single piece in GH₵', max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, help_text='Wholesale carton/bulk price in GH₵', max_digits=10)),
                ('wholesale_box_size', models.CharField(default='Box of 120', help_text='e.g. Box of 120, Carton of 48, Pack of 50', max_length=100)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('AVAILABLE_ON_ORDER', 'Available on Order'), ('BACKORDER_ALLOWED', 'Backorder Allowed')], default='IN_STOCK', max_length=25)),
                ('stock_quantity', models.PositiveIntegerField(default=100, help_text='Internal warehouse quantity. Strictly concealed from customers per company policy.')),
                ('icon_class', models.CharField(default='fas fa-book', help_text='Font Awesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_customizable', models.BooleanField(default=False, help_text='Can be ordered with custom school crests & rulings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
