# Generated by Django 5.2.7 on 2026-09-21 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='e.g. DSP-POS-1092', max_length=50, unique=True)),
                ('cashier_name', models.CharField(default='Solomon', max_length=100)),
                ('store_branch', models.CharField(default='Sunyani Main Branch', max_length=100)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash Counter'), ('MOMO_TILL', 'MTN Mobile Money Till'), ('TELECEL_CASH', 'Telecel Cash'), ('OTHER', 'Other')], default='CASH', max_length=25)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('items_summary', models.TextField(help_text='JSON or plain summary of items sold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Counter POS Sale',
                'verbose_name_plural': 'Sunyani Counter POS Sales',
                'ordering': ['-created_at'],
            },
        ),
    ]
